### ISSUE TITLE
Adding the ability to listen to a Podcast

### ISSUE THREAD

**Issue by marbetschar** [Suzie97/Communique#12]
## Problem

Its possible to subscribe to Podcasts using an RSS Feed. For example 60-Second Science: http://rss.sciam.com/sciam/60secsciencepodcast

It would be great to be able to listen to a Podcast directly from Communique.

## Proposal

Show audio controls to listen to the Podcast directly from within Communique if the currently selected article contains audio data.

## Prior Art

- Nextcloud News already provides the possibility to listen to Podcasts: https://github.com/nextcloud/news-android
- elementary Music can be a good example on how audio controls work: https://github.com/elementary/music

**Comment by Suzie97** [comment]
@marbetschar, Thank you so much for you suggestion.

But I want Communique to be a reading app. I want it to do one thing and do it well. A good podcast app should have podcast oriented features like speed control, trim silence, volume booster etc. 

The elementary team has also written about this on their [blog](https://blog.elementary.io/a-music-app-shouldnt-be-a-podcast-app/) and their [hig](https://docs.elementary.io/hig/design-philosophy/concision#avoid-feature-bloat).

AppCenter already has a podcast app [**Leopod**](https://appcenter.elementary.io/com.github.leggettc18.leopod/) and [Vocal](https://github.com/needle-and-thread/vocal) has also seen some recent development.

I'm closing the issue for now, feel free to reopen it if you have more points to share.
