### ISSUE TITLE
404 Page Not Found Error when setting up Inoreader

### ISSUE THREAD

**Issue by cedewey** [Suzie97/Communique#15]
## Describe the bug
404 Page Not Found Error when setting up Inoreader

I hit the Back button and tried connecting to Inoreader again and succeeded the second time.

## To Reproduce
1.  Click gear icon to get set up
2.  Choose Inoreader as my Feed reader
3. Login via google authentication
4. 404 page not found error displays

## Expected behavior
After logging into Inoreader I see my feeds.

## Screenshots
![communique-404-page-not-found](https://user-images.githubusercontent.com/1270531/150616999-e08901da-b29d-4a4e-a0cc-cc51869053a1.png)

## Platform Information
Linux ThinkPad 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="6.1 Jólnir"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 6.1 Jólnir"
LOGO=distributor-logo
VERSION_ID="6.1"
HOME_URL="https://elementary.io/"
DOCUMENTATION_URL="https://elementary.io/docs/learning-the-basics"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/triage/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=jolnir
UBUNTU_CODENAME=focal

**Comment by Suzie97** [comment]
> I hit the Back button and tried connecting to Inoreader again and succeeded the second time.

Hey @cedewey, thanks for reporting this issue. Since you succeeded the second time, I'm closing this issue. As it can be a problem with the network, or servers or the API.

Feel free to reopen this if you have more information to provide. We can investigate if there is any problem with the current Inoreader implementation in Communique.
