### ISSUE TITLE
Add the option to auto-start Communique in the background 

### ISSUE THREAD

**Issue by ghost** [Suzie97/Communique#18]
## Problem

Adding Communique to the startup applications will launch the whole application.

## Proposal

Communique should be able to start in the background when the computer boots.

## Prior Art

Some appcenter apps like elementary calendar, clips, reminduck etc.

**Comment by Suzie97** [comment]
@MakeGnomeWebFaster thanks for reporting. I've been working on this feature and it should be available in future updates. 👍🏼

**Comment by dCo3lh0** [comment]
adding here to the list, it would be great if it had a icon in system tray, checkbox options related to the systray, like minimize windows to system tray, close to system tray. and in the systray icon, options like Open Application, Update Feeds, Exit
