### ISSUE TITLE
Share to Nextcloud Bookmarks

### ISSUE THREAD

**Issue by ghost** [Suzie97/Communique#19]
## Proposal

Just like Pocket, sharing the article to Nextcloud Bookmarks could be a great option. Since the user is already able to sign in with a Nextcloud ID, I assume it'd be easier to implement this. Tags are also supported on both Communique and NC Bookmarks.

## Alternative Solutions

It's really optional and non-necessary feature.

## Prior Art

Couldn't find any. 😅️

**Comment by Suzie97** [comment]
> ## Proposal
> Just like Pocket, sharing the article to Nextcloud Bookmarks could be a great option. Since the user is already able to sign in with a Nextcloud ID, I assume it'd be easier to implement this. Tags are also supported on both Communique and NC Bookmarks.
> 
> ## Alternative Solutions
> It's really optional and non-necessary feature.
> 
> ## Prior Art
> Couldn't find any. 😅️

Thanks for this idea. I would be interested in implementing this. I didn't even know Nextcloud Bookmark existed.

**Comment by MakeGnomeWebFaster** [comment]
Sure yeah, I can test it. You can just tell me what to do.
