### ISSUE TITLE
Feed showing up as empty

### ISSUE THREAD

**Issue by ChildishGiant** [Suzie97/Communique#2]
This feed `https://ncase.me/feed.xml` (Attached for future reference [feed.xml.txt](https://github.com/Suzie97/Communique/files/7139953/feed.xml.txt)) shows no articles while other readers have no issue (I used https://rssatom.com/ to check)
![image](https://user-images.githubusercontent.com/13716824/132768397-60b5701a-d618-43b8-a9c1-234cd0352977.png)

**Comment by Suzie97** [comment]
@ChildishGiant sorry for the late response, I didn't know github doesn't send a notification of my own repo if I'm not watching it. 😅 . 

Can you see the articles when a new one arrives, or does it now show any article?
