### ISSUE TITLE
Disk read and write total is too high

### ISSUE THREAD

**Issue by ghost** [Suzie97/Communique#20]
## Describe the bug

Hi, it's me again! 😅️ As you can see below, Communique's disk write total is too high. I don't know what's causing this but let me know if I can help in any way.

## To Reproduce

1. Open the application
2. Let it run in the background for a while (an hour or so)
3. See that disk read and write is way too excessive for an app that's supposed to do nothing but watch new feeds.

## Expected behavior

Normal amount of disk read and write

## Screenshots

![comm](https://user-images.githubusercontent.com/98217801/151713752-b1f5789f-07ba-41bc-8501-7b3ea3556876.png)

## Platform Information

ElementaryOS 6, app is installed from Appcenter.

**Comment by Abdallah-Moh** [comment]
Maybe because it is a flatpak try another flatpak app and tell me the the read and write total

**Comment by MakeGnomeWebFaster** [comment]
What do you mean? Other flatpak apps' read write total can be seen in the screenshot above; Spot, Telegram desktop, Annotator (which is another appcenter app). Those are all flatpak and none of them have that problem.
