### ISSUE TITLE
Update GNOME runtime

### ISSUE THREAD

**Issue by UnderEu** [Suzie97/Communique#25]
## Problem
As I trigger my flatpak update script, it says:
Info: org.gnome.Platform//41 is end-of-life, with reason:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.suzie97.communique

## Proposal
Update the GNOME runtime to something newer, so the flatpak updater becomes happy about it.

**Comment by bbhtt** [comment]
Depends on https://github.com/Suzie97/Communique/issues/29
