### ISSUE TITLE
Provide a way to see the keyboard shortcuts in app

### ISSUE THREAD

**Issue by QWxleA** [Suzie97/Communique#3]
Great app! It works, it looks nice, 99% is done.

But it would be nice to at least **see** the keybindings. Changing them would be even nicer, but that would be more work.

**Comment by Suzie97** [comment]
> 
> 
> Great app! It works, it looks nice, 99% is done.
> 
> But it would be nice to at least **see** the keybindings. Changing them would be even nicer, but that would be more work.

A shortcut window will be added in the next update. Right now, you can see the keybindings in the AppCenter page.

**Comment by Suzie97** [comment]
Fixed in the latest release.
