### ISSUE TITLE
Local RSS looks ugly

### ISSUE THREAD

**Issue by QWxleA** [Suzie97/Communique#4]
![Screenshot from 2021-09-15 09-08-31](https://user-images.githubusercontent.com/24763887/133379818-471cb15b-95f1-4b27-9917-a5d4d1926381.png)

- The RSS symbol could be orange (maybe, not 100% on that one)
- "Communi...", that's just ugly, either reduce the font, or remove the half-word <--
- Local RSS is OK
- The whole thing looks too big

It's just a detail, definitely not a reason *not* to use the app, but it *did* annoy me a bit

**Comment by Abdallah-Moh** [comment]
@Suzie97, @QWxleA is right maybe give the grid a minimum size so it does not use ellipses

**Comment by Suzie97** [comment]
Hmm, I'm thinking of not showing the name of the service, and only show the logo with the username. 

We could just display Local in the same font size and not use the long Communique name, but the app also has Nextcloud News support which that is a long name too. And that cannot be shortened.

**Comment by QWxleA** [comment]
As far as I can see, it has no actual purpose. It is just to inform the user what backend is being used. Considering that changing accounts is not really supported (going back and forth I mean, not deleting one to start a new one), it is not something I'm ever likely to check.

It could either be completely removed or seen as decoration, in which case a nice icon/svg would be nicer to look at than some technical jargon and dots.

Nextcloud has an icon right?

**Comment by Abdallah-Moh** [comment]
yes

**Comment by Suzie97** [comment]
> As far as I can see, it has no actual purpose. It is just to inform the user what backend is being used. Considering that changing accounts is not really supported (going back and forth I mean, not deleting one to start a new one), it is not something I'm ever likely to check.
> 
> It could either be completely removed or seen as decoration, in which case a nice icon/svg would be nicer to look at than some technical jargon and dots.
> 
> Nextcloud has an icon right?

Yeah, not showing the service name and only the icon would be better, and every service has a logo, so that will work well.

**Comment by Suzie97** [comment]
This has been fixed in the latest release.
