### ISSUE TITLE
feedly secret expired

### ISSUE THREAD

**Issue by jangernert** [Suzie97/Communique#6]
A few weeks ago the feedly API secret of FeedReader that is still used in NewsFlash expired: https://gitlab.com/news-flash/news_flash/-/issues/66

This means the feedly integration as it exists now is broken. As you can see further down in the issue report I tried to apply for a new secret and was rejected. I doubt that its worth the try to apply for a secret for Communique. Communique stores the secret as clear-text in the git-repository. And obfuscating the secret is one of the base requirements.

There is the option to let users generate and enter developer API tokens. But these are quite limited in the number of API calls per day and the time they are valid.

I came to the conclusion to drop support for feedly from NewsFlash.

**Comment by Suzie97** [comment]
> A few weeks ago the feedly API secret of FeedReader that is still used in NewsFlash expired: https://gitlab.com/news-flash/news_flash/-/issues/66
> 
> This means the feedly integration as it exists now is broken. As you can see further down in the issue report I tried to apply for a new secret and was rejected. I doubt that its worth the try to apply for a secret for Communique. Communique stores the secret as clear-text in the git-repository. And obfuscating the secret is one of the base requirements.
> 
> There is the option to let users generate and enter developer API tokens. But these are quite limited in the number of API calls per day and the time they are valid.
> 
> I came to the conclusion to drop support for feedly from NewsFlash.

Yes, I'm aware that Feedly secret for FeedReader has expired, so it is not supported right now. 

I was about to apply for a new secret for Communique. But I didn't know that hiding the secret was a requirement.

**Comment by Suzie97** [comment]
I went through the discussion regarding Feedly support in NewsFlash, I'm pretty much convinced that supporting Feedly is not worth it. They have mentioned that they are more interested in working with projects that integrate with their Leo AI functionality.
