### ISSUE TITLE
Account setup should be shown on initial start

### ISSUE THREAD

**Issue by marbetschar** [Suzie97/Communique#9]
## Describe the bug

I just did a fresh installation of Communique from AppCenter and then started the app. After this initial start, it tried to somehow set its state to online and the spinner in the upper left corner just spinned endlessly.

So eventually I opened the settings by clicking on the gear icon and then choose "Change Account". After confirming the warning dialog, the account setup page appeared. There I was able to successfully add my Nextcloud News account.

## To Reproduce
1. Do a fresh installation of Communique from AppCenter
2. Start Communique
3. You'll end up in the main interface w/o any hints about setting up a new account

## Expected behavior

After Communique is freshly installed and started, it should display the "Setting up a new account" page immediately, because there is nothing else to display.

Maybe it makes sense to always display the account setup if there aren't any accounts setup - regardless if it is the first time Communique was started.

## Platform Information

Latest elementary OS v6 (stable). Installed latest Communique from AppCenter.

**Comment by tooManyArguments** [comment]
Same issue here and agree with OP, this took a few minutes of wondering what was going on.

**Comment by tr1p0p** [comment]
Yeah can you... Think about the user ?

Yeah i know, it's crazy to thing about that.

(I uninstall the app off course)
